# Form implementation generated from reading ui file '.\roadyGUI.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from roady import Roady

from tkinter import messagebox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(557, 454)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.departure_city_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.departure_city_label.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.departure_city_label.setObjectName("departure_city_label")
        self.departure_city_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.departure_city_input.setGeometry(QtCore.QRect(110, 10, 113, 21))
        self.departure_city_input.setObjectName("departure_city_input")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 10, 91, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(380, 10, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.gas_combo_box = QtWidgets.QComboBox(parent=self.centralwidget)
        self.gas_combo_box.setGeometry(QtCore.QRect(10, 50, 68, 22))
        self.gas_combo_box.setObjectName("gas_combo_box")
        self.gas_combo_box.addItem("")
        self.gas_combo_box.addItem("")
        self.consum_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.consum_label.setGeometry(QtCore.QRect(10, 80, 49, 16))
        self.consum_label.setObjectName("consum_label")
        self.fuel_usage = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.fuel_usage.setGeometry(QtCore.QRect(70, 80, 113, 21))
        self.fuel_usage.setObjectName("fuel_usage")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 49, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 120, 41, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.calculate_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.calculate_button.clicked.connect(self.calculate_btn)
        self.calculate_button.setGeometry(QtCore.QRect(200, 150, 151, 51))
        self.calculate_button.setObjectName("calculate_button")
        self.add_return_radio_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.add_return_radio_button.setGeometry(QtCore.QRect(170, 50, 89, 20))
        self.add_return_radio_button.setObjectName("add_return_radio_button")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(180, 210, 191, 191))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(".\\DSC0101.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 557, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.departure_city_label.setText(_translate("MainWindow", "Departure City"))
        self.label.setText(_translate("MainWindow", "Destination City"))
        self.gas_combo_box.setItemText(0, _translate("MainWindow", "Benzina"))
        self.gas_combo_box.setItemText(1, _translate("MainWindow", "Diesel"))
        self.consum_label.setText(_translate("MainWindow", "Consum"))
        self.label_2.setText(_translate("MainWindow", "Persons"))
        self.calculate_button.setText(_translate("MainWindow", "Calculate"))
        self.add_return_radio_button.setText(_translate("MainWindow", "Dus/Intors"))

    def calculate_btn(self):
        departure_city = self.departure_city_input.text()
        destination_city = self.lineEdit.text()
        number_of_persons = self.lineEdit_2.text()
        fuel_type = self.gas_combo_box.currentText()
        fuel_usage = self.fuel_usage.text()
        roady = Roady(departure_city, destination_city,
                      int(number_of_persons), float(fuel_usage), fuel_type)

        price = roady.calculate_price_per_person()
        if self.add_return_radio_button.isEnabled():
            messagebox.showinfo(f"Calculation result", f"the price per person is {price * 2}")
        else:
            messagebox.showinfo("Calculation Result", f"The price per person is: {price}")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
